[project]
name = "dbt-bigquery-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dbt-bigquery>=1.12.0",
    "dbt-core>=1.12.3",
]

[project.scripts]
dbt-bigquery-project = "dbt_bigquery_project:main"

[build-system]
requires = ["uv_build>=0.12.4,<0.13.0"]
build-backend = "uv_build"
